### PR TITLE
Playground style updates

### PR DESCRIPTION
**Pull request by sanntu**
- Added diagonal lines to layout.
- Little adjusts for correct implementation.

### CODE REVIEW

**Comment by cabralmartin** [comment]
@sanntu Please delete the `index.css.map` file. It is not necessary. Better yet, lets add it to the `.gitignore`.

**Comment by sanntu** [comment]
I'll do that.

**Comment by cabralmartin** [comment]
@gnandretta can you confirm we are not using css maps anywhere on the lock? We want to exclude a map we auto generate in the playground, so the question is, is it ok to add the following line to `.gitignore`?

`.css.map`

**Comment by gnandretta** [comment]
@cabralmartin go ahead

**Comment by cabralmartin** [comment]
thanks @gnandretta! this is good to merge :)

**Comment by gnandretta** [comment]
Thanks!

**Pull request merged**
