### PR TITLE
use latest react version

### PR DESCRIPTION
**Pull request by gerbenmeyer**
The react version used was very outdated, so I updated it.

### CODE REVIEW

**Comment by arnihermann** [comment]
This is a blocker for me.

@gnandretta do you think it's possible to get a release out with updated dependencies soon?

**Comment by jeffgorder** [comment]
It would be great to get this released.

**Comment by XaserAcheron** [comment]
Though I know work's being done on moving passwordless to Lock itself, the React version difference is the source of [some trickiness](https://github.com/auth0-community/ember-simple-auth-auth0/issues/89) in the Ember addon. It would make life a ton easier to get this merged in.

If this needs additional testing before merge, I'll be happy to help.

[Hope I'm not abusing the privilege, but I'll ping @aaguiarz since he's been active and lending a hand as of late.]

**Comment by luisrudge** [comment]
Hi @XaserAcheron, we're actually merging Passwordless and Lock in a single project. You can follow the progress [here](https://github.com/auth0/lock/pull/1070). There'll be no active development on this project anymore. We'll fix security issues only for the near future.

**Comment by luisrudge** [comment]
if you use yarn, you can pin the dependencies you want using the resolutions property. Sadly, it's not a minor update, since there were a lot of react upgrades between 0.14.0 and 15.4.2. We just can't justify investing more time debugging and make sure this works everywhere, since we're already putting a lot of effort in merging both Lock and Passwordless. I'm sorry you're being put through this. I promise you the new Lock+Passwordless will be amazing. If you want to use the new version (knowing we don't have proper support for it yet), please try `npm install auth0/lock#feature-add-pwdless`. The draft of the migration guide is located here: https://github.com/auth0/docs/pull/5016

The feature itself is finished. We had to put it on hold for now because we're releasing major versions of both auth0-js and lock and we don't want to conflate both releases.

Again, I'm sorry you're stuck in this "limbo" phase while we are putting things in order. Let me know if I can help you in any other way.

**Comment by XaserAcheron** [comment]
It's all good -- apologies for being a bit grumpy earlier.

Knowing that the feature is in finished draft stage actually helps a ton -- that gives me enough confidence to start trying it out. It seems more prudent to work on supporting the new API in the Ember addon rather than try and resolve the dependency differences, which I think works out best for everyone.

Hooray for progress!

**Pull request closed without merging**
